Repository celestiaorg/orchestrator-relayer, pull requests merged in 2023-11, with the labels that each got.

#569 ci: remove the duplicate CI runs
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: CI/CD

#576 feat: support secure grpc connections
  cmd/blobstream/base/config.go
  cmd/blobstream/common/helpers.go
  cmd/blobstream/deploy/cmd.go
  cmd/blobstream/deploy/config.go
  cmd/blobstream/orchestrator/cmd.go
  cmd/blobstream/orchestrator/config.go
  cmd/blobstream/query/cmd.go
  cmd/blobstream/query/config.go
  cmd/blobstream/relayer/cmd.go
  cmd/blobstream/relayer/config.go
  e2e/qgb_network.go
  e2e/relayer_test.go
  e2e/scripts/deploy_blobstream_contract.sh
  e2e/scripts/start_orchestrator_after_validator_created.sh
  e2e/scripts/start_relayer.sh
  orchestrator/orchestrator_test.go
  rpc/app_querier.go
  rpc/app_querier_test.go
  testing/qgb.go
Labels: orchestrator, relayer

#571 feat: use archive nodes to query attestations
  cmd/blobstream/deploy/cmd.go
  cmd/blobstream/deploy/config.go
  cmd/blobstream/deploy/errors.go
  e2e/scripts/deploy_blobstream_contract.sh
  orchestrator/orchestrator_test.go
  orchestrator/suite_test.go
  relayer/historic_relayer_test.go
  relayer/historic_suite_test.go
  relayer/relayer.go
  relayer/relayer_test.go
  rpc/app_historic_querier_test.go
  rpc/app_querier.go
  rpc/errors.go
  rpc/historic_suite_test.go
  testing/celestia_network.go
Labels: enhancement, relayer

#577 feat: adds support for BIP39 mnemonics
  cmd/blobstream/keys/evm/evm.go
  cmd/blobstream/keys/evm/evm_test.go
  go.mod
Labels: store, evm

#582 chore(deps): bump blobstream to v4
  benchmark/main.go
  cmd/blobstream/deploy/cmd.go
  cmd/blobstream/relayer/cmd.go
  e2e/go.mod
  e2e/go.sum
  e2e/qgb_network.go
  evm/evm_client.go
  evm/evm_client_test.go
  go.mod
  go.sum
  relayer/relayer.go
Labels: dependencies

#583 feat: support using config files for orchestrator and relayer
  cmd/blobstream/base/config.go
  cmd/blobstream/deploy/config.go
  cmd/blobstream/keys/evm/evm.go
  cmd/blobstream/orchestrator/cmd.go
  cmd/blobstream/orchestrator/config.go
  cmd/blobstream/query/config.go
  cmd/blobstream/relayer/cmd.go
  cmd/blobstream/relayer/config.go
  e2e/scripts/deploy_blobstream_contract.sh
  e2e/scripts/start_orchestrator_after_validator_created.sh
  e2e/scripts/start_relayer.sh
  go.mod
Labels: orchestrator, relayer

#585 docs: add config files documentation
  docs/deploy.md
  docs/orchestrator.md
  docs/relayer.md
Labels: documentation

#591 feat: support log level and log format flags
  cmd/blobstream/base/config.go
  cmd/blobstream/bootstrapper/cmd.go
  cmd/blobstream/bootstrapper/config.go
  cmd/blobstream/deploy/cmd.go
  cmd/blobstream/deploy/config.go
  cmd/blobstream/keys/evm/config.go
  cmd/blobstream/keys/evm/evm.go
  cmd/blobstream/keys/p2p/config.go
  cmd/blobstream/keys/p2p/p2p.go
  cmd/blobstream/orchestrator/cmd.go
  cmd/blobstream/orchestrator/config.go
  cmd/blobstream/relayer/cmd.go
  cmd/blobstream/relayer/config.go
  e2e/scripts/deploy_blobstream_contract.sh
  go.mod
  orchestrator/orchestrator.go
  p2p/querier.go
  relayer/relayer.go
Labels: enhancement

#592 docs: improve orchestrator documentation
  docs/orchestrator.md
Labels: documentation

#597 chore: dependabot for e2e
  .github/dependabot.yml
Labels: chore

#596 docs: fix grammar and remove patch number from Go version
  README.md
Labels: documentation

#598 chore: `.PHONY` targets for Make commands
  Makefile
Labels: chore

#602 docs: specify that validators should generate EVM addresses offchain
  docs/orchestrator.md
Labels: documentation

#601 docs: update README to specify that a relayer can be run to an existing contract
  README.md
Labels: documentation

#603 chore: implement blobstream feedback from docs #1275
  docs/keys.md
  docs/orchestrator.md
  docs/relayer.md
Labels: documentation

#604 chore: add placeholder for mocha bootstrapper
  docs/orchestrator.md
Labels: documentation

#609 chore: make the already signed log debug level
  orchestrator/orchestrator.go
Labels: chore

#610 chore: update docs
  docs/orchestrator.md
Labels: documentation

#611 chore: make the validator not part of valset log info level
  orchestrator/orchestrator.go
Labels: chore

#622 chore: rename residual QGB mentions to Blobstream
  benchmark/main.go
  evm/evm_client.go
  orchestrator/orchestrator_test.go
  relayer/relayer_test.go
  store/init.go
  testing/blobstream.go
  testing/celestia_network.go
Labels: chore

#621 feat: add timeout when waiting for transaction to be minted
  benchmark/main.go
  cmd/blobstream/base/config.go
  cmd/blobstream/deploy/cmd.go
  cmd/blobstream/relayer/cmd.go
  cmd/blobstream/relayer/config.go
  evm/evm_client.go
  relayer/relayer.go
  relayer/relayer_test.go
  testing/blobstream.go
Labels: enhancement, relayer

#619 feat: support getting config from homes for query commands
  cmd/blobstream/orchestrator/config.go
  cmd/blobstream/query/cmd.go
  cmd/blobstream/query/config.go
  cmd/blobstream/relayer/config.go
Labels: enhancement

#626 docs: document the importance of running orchestrator
  README.md
  docs/orchestrator.md
Labels: documentation, orchestrator

#627 feat: add moniker and valoper address to signatures query
  cmd/blobstream/query/cmd.go
  rpc/app_querier.go
Labels: enhancement, orchestrator

#617 docs: document updating the EVM address for validators
  docs/orchestrator.md
Labels: documentation, orchestrator

#630 chore: log the version when starting orchestrator and relayer
  cmd/blobstream/orchestrator/cmd.go
  cmd/blobstream/relayer/cmd.go
Labels: orchestrator, relayer, chore
