Repository celestiaorg/orchestrator-relayer, pull requests merged in 2023-09, with the labels that each got.

#464 documentation: match frontmatter on docs site .md files
  docs/deploy.md
  docs/keys.md
  docs/orchestrator.md
  docs/relayer.md
Labels: documentation

#459 chore(deps): bump go to v1.21 and other dependencies
  .github/workflows/lint.yml
  .github/workflows/tag.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  e2e/Dockerfile_e2e
  go.mod
  go.sum
Labels: dependencies

#469 chore(deps): bump contracts version and update EVM deployments to support the upgradable proxy
  cmd/qgb/deploy/cmd.go
  cmd/qgb/relayer/cmd.go
  e2e/Dockerfile_e2e
  e2e/docker-compose.yml
  e2e/qgb_network.go
  e2e/scripts/start_relayer.sh
  evm/evm_client.go
  go.mod
  go.sum
Labels: enhancement, relayer, dependencies, evm

#468 fix: makefile repo version
  Makefile
Labels: bug, chore

#474 docs: add registering EVM address instructions
  docs/orchestrator.md
Labels: documentation, orchestrator, evm

#477 docs: add bootstrapper command docs
  docs/bootstrapper.md
Labels: documentation, p2p

#478 chore: update the bootstrapper command description
  cmd/qgb/bootstrapper/cmd.go
Labels: documentation, p2p

#482 chore(deps): bump go version to v1.21.1
  .github/workflows/lint.yml
  .github/workflows/tag.yml
  .github/workflows/test.yml
  Makefile
  go.mod
Labels: dependencies

#480 chore(docs): confusing p2p key necessity in bootstrapper docs
  docs/bootstrapper.md
Labels: documentation

#489 chore(deps): bump app to rc17
  cmd/qgb/relayer/cmd.go
  e2e/qgb_network.go
  evm/evm_client.go
  evm/evm_client_test.go
  go.mod
  go.sum
  relayer/relayer.go
Labels: dependencies

#484 ci: fix makefile docker image build
  Makefile
  docker/entrypoint.sh
Labels: CI/CD

#492 docs: mention the EVM key registeration when start orchestrator
  docs/orchestrator.md
Labels: documentation

#497 chore: reduce the default EVM gas limit
  evm/evm_client.go
Labels: evm

#490 chore(deps): bump e2e dockerfile app version to rc17
  e2e/Dockerfile_e2e
Labels: dependencies
