Repository celestiaorg/orchestrator-relayer, pull requests merged in 2023-10, with the labels that each got.

#509 chore(deps): bump golang ci linter version
  .github/workflows/lint.yml
Labels: dependencies

#508 chore(deps): bump app to rc18
  e2e/Dockerfile_e2e
  e2e/celestia-app/app.toml
  e2e/docker-compose.yml
  go.mod
  go.sum
Labels: dependencies

#511 docs: implement "no click here" on QGB docs
  docs/bootstrapper.md
  docs/deploy.md
  docs/keys.md
  docs/orchestrator.md
  docs/relayer.md
Labels: documentation

#504 ci: add support for codeql
  .github/workflows/codeql.yml
Labels: CI/CD

#521 fix: make the orchestrator sign by default
  orchestrator/orchestrator.go
  orchestrator/orchestrator_test.go
  orchestrator/suite_test.go
  relayer/suite_test.go
  rpc/suite_test.go
  testing/celestia_network.go
  testing/testnode.go
Labels: bug, orchestrator

#514 chore(docs): update QGB to "Blobstream"
  docs/bootstrapper.md
  docs/deploy.md
  docs/keys.md
  docs/orchestrator.md
  docs/relayer.md
Labels: documentation

#529 fix: handle first nonce in orchestrator
  orchestrator/orchestrator.go
Labels: enhancement

#531 chore: not sign nonce 1
  orchestrator/orchestrator.go
Labels: chore

#532 chore: increase relayer delay
  e2e/scripts/start_relayer.sh
Labels: chore

#519 chore(deps): bump E2E app version to 1.0.0
  e2e/Dockerfile_e2e
Labels: chore

#544 chore: bump app version to v1.1.0 in e2e
  e2e/Dockerfile_e2e
Labels: dependencies, chore

#551 chore: fix multiplatform builds
  Dockerfile
Labels: CI/CD

#550 chore(deps): depend on blobstream contracts
  cmd/blobstream/relayer/cmd.go
  e2e/go.mod
  e2e/go.sum
  e2e/qgb_network.go
  evm/evm_client.go
  evm/evm_client_test.go
  go.mod
  go.sum
  relayer/relayer.go
Labels: dependencies

#554 ci: add e2e go.mod to dependabot
  .github/dependabot.yml
Labels: CI/CD

#555 feat: orchestrator signing up to earliest attestation nonce
  e2e/Dockerfile_e2e
  orchestrator/orchestrator.go
  rpc/app_querier.go
  rpc/app_querier_test.go
Labels: enhancement, orchestrator

#524 feat: add gas cost benchmark tool
  benchmark/main.go
Labels: enhancement

#561 fix: update QGB to Blobstream in benchmark
  benchmark/main.go
Labels: chore

#565 feat: add version command
  Makefile
  cmd/blobstream/root/cmd.go
  cmd/blobstream/version/build_info.go
  cmd/blobstream/version/version.go
Labels: enhancement, chore

#564 chore(deps): bump app to v1.3.0
  e2e/Dockerfile_e2e
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: dependencies, chore

#560 feat: gossiping the latest valset in P2P layer in case they get pruned
  cmd/blobstream/deploy/cmd.go
  evm/evm_client.go
  orchestrator/broadcaster.go
  orchestrator/broadcaster_test.go
  orchestrator/orchestrator.go
  orchestrator/orchestrator_test.go
  p2p/dht.go
  p2p/dht_test.go
  p2p/errors.go
  p2p/keys.go
  p2p/querier.go
  p2p/validators.go
  p2p/validators_test.go
  relayer/errors.go
  relayer/relayer.go
  relayer/relayer_test.go
  types/latest_valset.go
  types/latest_valset_test.go
Labels: p2p, orchestrator, relayer

#567 ci: add support for goreleaser
  .github/workflows/ci-release.yml
  .goreleaser.yaml
Labels: CI/CD

#568 ci: allow for test workflow call
  .github/workflows/test.yml
Labels: CI/CD

#558 chore: resolve issues on docs runtime with use of ssh instead of sh
  docs/bootstrapper.md
  docs/deploy.md
  docs/keys.md
  docs/orchestrator.md
  docs/relayer.md
Labels: documentation
