Repository celestiaorg/orchestrator-relayer, pull requests merged in 2024-01, with the labels that each got.

#674 feat: add metrics to orchestrator and relayer
  cmd/blobstream/base/config.go
  cmd/blobstream/bootstrapper/cmd.go
  cmd/blobstream/common/helpers.go
  cmd/blobstream/orchestrator/cmd.go
  cmd/blobstream/orchestrator/config.go
  cmd/blobstream/relayer/cmd.go
  cmd/blobstream/relayer/config.go
  e2e/celestia-app/genesis.json
  e2e/docker-compose.yml
  e2e/go.mod
  e2e/go.sum
  e2e/scripts/start_orchestrator_after_validator_created.sh
  e2e/scripts/start_relayer.sh
  e2e/telemetry/grafana/datasources/config.yml
  e2e/telemetry/otel-collector/config.yml
  e2e/telemetry/prometheus/prometheus.yml
  go.mod
  go.sum
  go.work.sum
  orchestrator/orchestrator.go
  p2p/host.go
  p2p/host_test.go
  relayer/relayer.go
  telemetry/metrics.go
  testing/blobstream.go
Labels: enhancement, orchestrator, relayer

#675 docs: metrics documentation
  docs/orchestrator.md
  docs/relayer.md
Labels: documentation

#682 doc: typo
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: documentation, chore

#688 chore: bump go version to v1.21.6
  .github/workflows/ci-release.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/tag.yml
  .github/workflows/test.yml
  e2e/Dockerfile_e2e
  e2e/go.mod
  go.mod
Labels: dependencies, chore

#690 chore: rename the dependabot reviewer name
  .github/dependabot.yml
Labels: chore
